saleor/order/urls.py
from django.conf.urls import patterns, url

from . import views


TOKEN_PATTERN = ('(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}'
                 '-[0-9a-z]{12})')

urlpatterns = patterns(
    '',
    url(r'^%s/$' % TOKEN_PATTERN, views.details, name='details'),
    url(r'^%s/payment/(?P<variant>\w+)/$' % TOKEN_PATTERN, views.start_payment,
        name='payment'),
    url(r'^%s/cancel-payment/$' % TOKEN_PATTERN, views.cancel_payment,
        name='cancel-payment'))

saleor/registration/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^oauth_callback/(?P<service>\w+)/$', views.oauth_callback,
        name='oauth_callback'),
    url(r'^change_password/$', views.change_password,
        name='change_password'),
    url(r'^request_email_confirmation/$', views.request_email_confirmation,
        name='request_email_confirmation'),
    url(r'^confirm_email/(?P<token>\w+)/$', views.confirm_email,
        name='confirm_email'),
    url(r'^request_email_change/$', views.request_email_change,
        name='request_email_change'),
    url(r'^change_email/(?P<token>\w+)/$', views.change_email,
        name='change_email'))

saleor/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib import admin


from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .ricette.urls import urlpatterns as ricette_urls

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$',                  include(core_urls),             name='home'),
    url(r'^account/',           include(registration_urls,      namespace='registration')),
    url(r'^admin/',             include(admin.site.urls)),
    url(r'^cart/',              include(cart_urls,              namespace='cart')),
    url(r'^checkout/',          include(checkout_urls,          namespace='checkout')),
    url(r'^images/',            include('django_images.urls')),
    url(r'^order/',             include(order_urls,             namespace='order')),
    url(r'^products/',          include(product_urls,           namespace='product')),
    url(r'^profile/',           include(userprofile_urls,       namespace='profile')),
    url(r'^selectable/',        include('selectable.urls')),
    url(r'^ricette/',           include(ricette_urls,         namespace='ricette')),
    url(r'',                    include('payments.urls'))
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns(
        '',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}))

saleor/userprofile/urls.py
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns(
    '',
    url(r'^$', views.details, name='details'),
    url(r'^orders/$', views.orders, name='orders'),
    url(r'^address/create/$', views.address_create,
        name='address-create'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/edit/$', views.address_edit,
        name='address-edit'),
    url(r'^address/(?P<slug>[\w-]+)-(?P<pk>\d+)/delete/$',
        views.address_delete, name='address-delete'),
    url(r'^address/(?P<pk>\d+)/make-default-for-'
        r'(?P<purpose>billing|shipping)/$', views.address_make_default,
        name='address-make-default')
)

saleor/order/models.py
from __future__ import unicode_literals
from decimal import Decimal

from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import smart_text
from django.utils.timezone import now
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import pgettext_lazy
from django_prices.models import PriceField
from payments import PurchasedItem
from payments.models import BasePayment
from prices import Price
from satchless.item import ItemSet, ItemLine
from uuid import uuid4

from ..communication.mail import send_email
from ..core.utils import build_absolute_uri
from ..core.utils.models import Subtyped
from ..product.models import Product
from ..userprofile.models import Address


@python_2_unicode_compatible
class Order(models.Model, ItemSet):

    STATUS_CHOICES = (
        ('new', pgettext_lazy('Order status field value', 'Processing')),
        ('cancelled', pgettext_lazy('Order status field value',
                                    'Cancelled')),
        ('payment-pending', pgettext_lazy('Order status field value',
                                          'Waiting for payment')),
        ('fully-paid', pgettext_lazy('Order status field value',
                                     'Fully paid')),
        ('shipped', pgettext_lazy('Order status field value',
                                  'Shipped')))
    status = models.CharField(
        pgettext_lazy('Order field', 'order status'),
        max_length=32, choices=STATUS_CHOICES, default='new')
    created = models.DateTimeField(
        pgettext_lazy('Order field', 'created'),
        default=now, editable=False)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Order field', 'last status change'),
        default=now, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='orders',
        verbose_name=pgettext_lazy('Order field', 'user'))
    tracking_client_id = models.CharField(max_length=36, blank=True,
                                          editable=False)
    billing_address = models.ForeignKey(Address, related_name='+',
                                        editable=False)
    anonymous_user_email = models.EmailField(blank=True, default='',
                                             editable=False)
    token = models.CharField(
        pgettext_lazy('Order field', 'token'),
        max_length=36, blank=True, default='')

    class Meta:
        ordering = ('-last_status_change',)

    def save(self, *args, **kwargs):
        if not self.token:
            for _i in range(100):
                token = str(uuid4())
                if not type(self).objects.filter(token=token).exists():
                    self.token = token
                    break
        return super(Order, self).save(*args, **kwargs)

    def change_status(self, status):
        self.status = status
        self.save()

    def get_items(self):
        return OrderedItem.objects.filter(delivery_group__order=self)

    def is_fully_paid(self):
        total_paid = sum([payment.total for payment in
                          self.payments.filter(status='confirmed')], Decimal())
        total = self.get_total()
        return total_paid >= total.gross

    def get_user_email(self):
        if self.user:
            return self.user.email
        return self.anonymous_user_email

    def __iter__(self):
        return iter(self.groups.all())

    def __repr__(self):
        return '<Order #%r>' % (self.id,)

    def __str__(self):
        return '#%d' % (self.id, )

    @property
    def billing_full_name(self):
        return '%s %s' % (self.billing_first_name, self.billing_last_name)

    def get_absolute_url(self):
        return reverse('order:details', kwargs={'token': self.token})

    def get_delivery_total(self):
        return sum([group.price for group in self.groups.all()],
                   Price(0, currency=settings.DEFAULT_CURRENCY))

    def send_confirmation_email(self):
        email = self.get_user_email()
        payment_url = build_absolute_uri(
            reverse('order:details', kwargs={'token': self.token}))
        context = {'payment_url': payment_url}
        send_email(email, 'order/emails/confirm_email.txt', context)


class DeliveryGroup(Subtyped, ItemSet):
    STATUS_CHOICES = (
        ('new',
         pgettext_lazy('Delivery group status field value', 'Processing')),
        ('cancelled', pgettext_lazy('Delivery group status field value',
                                    'Cancelled')),
        ('shipped', pgettext_lazy('Delivery group status field value',
                                  'Shipped')))
    status = models.CharField(
        pgettext_lazy('Delivery group field', 'Delivery status'),
        max_length=32, default='new', choices=STATUS_CHOICES)
    method = models.CharField(
        pgettext_lazy('Delivery group field', 'Delivery method'),
        max_length=255)
    order = models.ForeignKey(Order, related_name='groups', editable=False)
    price = PriceField(
        pgettext_lazy('Delivery group field', 'unit price'),
        currency=settings.DEFAULT_CURRENCY, max_digits=12,
        decimal_places=4,
        default=0,
        editable=False)

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, list(self))

    def __iter__(self):
        if self.id:
            return iter(self.items.select_related('product').all())
        return super(DeliveryGroup, self).__iter__()

    def change_status(self, status):
        self.status = status
        self.save()

    def get_total(self, **kwargs):
        return super(DeliveryGroup, self).get_total(**kwargs) + self.price

    def add_items_from_partition(self, partition):
        for item_line in partition:
            product_variant = item_line.product
            price = item_line.get_price_per_item()
            self.items.create(
                product=product_variant.product,
                quantity=item_line.get_quantity(),
                unit_price_net=price.net,
                product_name=smart_text(product_variant),
                product_sku=product_variant.sku,
                unit_price_gross=price.gross)


@python_2_unicode_compatible
class ShippedDeliveryGroup(DeliveryGroup):

    address = models.ForeignKey(Address, related_name='+')

    def __str__(self):
        return 'Shipped delivery'


@python_2_unicode_compatible
class DigitalDeliveryGroup(DeliveryGroup):

    email = models.EmailField()

    def __str__(self):
        return 'Digital delivery'


@python_2_unicode_compatible
class OrderedItem(models.Model, ItemLine):

    delivery_group = models.ForeignKey(
        DeliveryGroup, related_name='items', editable=False)
    product = models.ForeignKey(
        Product, blank=True, null=True, related_name='+',
        on_delete=models.SET_NULL,
        verbose_name=pgettext_lazy('OrderedItem field', 'product'))
    product_name = models.CharField(
        pgettext_lazy('OrderedItem field', 'product name'), max_length=128)
    product_sku = models.CharField(pgettext_lazy('OrderedItem field', 'sku'),
                                   max_length=32)
    quantity = models.DecimalField(
        pgettext_lazy('OrderedItem field', 'quantity'),
        max_digits=10, decimal_places=4)
    unit_price_net = models.DecimalField(
        pgettext_lazy('OrderedItem field', 'unit price (net)'),
        max_digits=12, decimal_places=4)
    unit_price_gross = models.DecimalField(
        pgettext_lazy('OrderedItem field', 'unit price (gross)'),
        max_digits=12, decimal_places=4)

    def get_price_per_item(self, **kwargs):
        return Price(net=self.unit_price_net, gross=self.unit_price_gross,
                     currency=settings.DEFAULT_CURRENCY)

    def __str__(self):
        return self.product_name

    def get_quantity(self):
        return self.quantity


class Payment(BasePayment):

    order = models.ForeignKey(Order, related_name='payments')

    def get_failure_url(self):
        return build_absolute_uri(
            reverse('order:details', kwargs={'token': self.order.token}))

    def get_success_url(self):
        return build_absolute_uri(
            reverse('order:details', kwargs={'token': self.order.token}))

    def send_confirmation_email(self):
        email = self.order.get_user_email()
        order_url = build_absolute_uri(
            reverse('order:details', kwargs={'token': self.order.token}))
        context = {'order_url': order_url}
        send_email(email, 'order/payment/emails/confirm_email.txt', context)

    def get_purchased_items(self):
        items = [PurchasedItem(name=item.product_name, quantity=item.quantity,
                               price=item.unit_price_gross,
                               sku=item.product.sku,
                               currency=settings.DEFAULT_CURRENCY)
                 for item in self.order.get_items()]
        return items

saleor/order/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext_lazy as _

from .models import Payment


class PaymentMethodsForm(forms.Form):

    method = forms.ChoiceField(choices=settings.CHECKOUT_PAYMENT_CHOICES)


class PaymentDeleteForm(forms.Form):

    payment_id = forms.IntegerField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        super(PaymentDeleteForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(PaymentDeleteForm, self).clean()
        payment_id = cleaned_data.get('payment_id')
        waiting_payments = self.order.payments.filter(status='waiting')
        try:
            payment = waiting_payments.get(id=payment_id)
        except Payment.DoesNotExist:
            self._errors['number'] = self.error_class(
                [_('Payment does not exist')])
        else:
            cleaned_data['payment'] = payment
        return cleaned_data

    def save(self):
        payment = self.cleaned_data['payment']
        payment.status = 'rejected'
        payment.save()

saleor/order/views.py
from django.db import transaction
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from payments import RedirectNeeded

from . import check_order_status
from .forms import PaymentDeleteForm, PaymentMethodsForm
from .models import Order, Payment


def details(request, token):
    order = get_object_or_404(Order, token=token)
    groups = order.groups.all()
    payments = order.payments.all()
    form_data = request.POST or None
    try:
        waiting_payment = order.payments.get(status='waiting')
    except Payment.DoesNotExist:
        waiting_payment = None
        waiting_payment_form = None
    else:
        form_data = None
        waiting_payment_form = PaymentDeleteForm(
            None, order=order, initial={'payment_id': waiting_payment.id})
    if order.is_fully_paid():
        form_data = None
    payment_form = PaymentMethodsForm(form_data)
    if payment_form.is_valid():
        payment_method = payment_form.cleaned_data['method']
        return redirect('order:payment', token=order.token,
                        variant=payment_method)
    return TemplateResponse(request, 'order/details.html',
                            {'order': order, 'groups': groups,
                             'payment_form': payment_form,
                             'waiting_payment': waiting_payment,
                             'waiting_payment_form': waiting_payment_form,
                             'payments': payments})


@check_order_status
def start_payment(request, order, variant):
    waiting_payments = order.payments.filter(status='waiting').exists()
    if waiting_payments:
        return redirect('order:details', token=order.token)
    billing = order.billing_address
    total = order.get_total()
    defaults = {'total': total.gross,
                'tax': total.tax, 'currency': total.currency,
                'delivery': order.get_delivery_total().gross,
                'billing_first_name': billing.first_name,
                'billing_last_name': billing.last_name,
                'billing_address_1': billing.street_address_1,
                'billing_address_2': billing.street_address_2,
                'billing_city': billing.city,
                'billing_postcode': billing.postal_code,
                'billing_country_code': billing.country,
                'billing_country_area': billing.country_area}
    with transaction.atomic():
        order.change_status('payment-pending')
        payment, _created = Payment.objects.get_or_create(variant=variant,
                                                          status='waiting',
                                                          order=order,
                                                          defaults=defaults)
        try:
            form = payment.get_form(data=request.POST or None)
        except ValueError as e:
            raise Http404(e)
        except RedirectNeeded as redirect_to:
            return redirect(str(redirect_to))
    template = 'order/payment/%s.html' % variant
    return TemplateResponse(request, [template, 'order/payment/default.html'],
                            {'form': form, 'payment': payment})


@check_order_status
def cancel_payment(request, order):
    form = PaymentDeleteForm(request.POST or None, order=order)
    if form.is_valid():
        with transaction.atomic():
            form.save()
        return redirect('order:details', token=order.token)
    return HttpResponseForbidden()

saleor/userprofile/templates/userprofile/ajax/address-delete.html
{% load i18n %}

{% block content %}
    <h2>{% trans "Are you sure you want to delete the following address?" %}</h2>
    <address>{% include "userprofile/snippets/address-details.html" with address=object.address %}</address>
    <form action="." method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">{% trans "Delete" %}</button>
        <a href="{% url 'profile:details' %}" class="btn btn-link">{% trans "Cancel" %}</a>
    </form>
{% endblock content %}

saleor/userprofile/templates/userprofile/ajax/address-edit.html
{% load as_horizontal_form from bootstrap %}
{% load i18n %}
<form class="form-horizontal" action="." method="post">
    {% csrf_token %}
    <fieldset>
        <legend>Address</legend>
        {{ address_book_form|as_horizontal_form }}
        {{ address_form|as_horizontal_form }}
    </fieldset>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="{% url 'profile:details' %}" class="btn btn-link">Cancel</a>
        </div>
    </div>
</form>

saleor/userprofile/templates/userprofile/ajax/details.html
{% load i18n %}
<h2>{% trans "Profile" %}</h2>
<p>
    <a href="{% url 'registration:change_password' %}" class="btn btn-default">{% trans 'Change your password' %}</a>
    <a href="{% url 'registration:request_email_change' %}" class="btn btn-default">{% trans 'Change your email address' %}</a>
</p>


<h3>{% trans "Your address book" %}</h3>
<table class="table table-striped">
    <thead>
        <tr>
            <th class="col-sm-2">{% trans "Short alias" %}</th>
            <th class="col-sm-4">{% trans "Addressee" %}</th>
            <th class="col-sm-2">{% trans "Billing" %}</th>
            <th class="col-sm-2">{% trans "Shipping" %}</th>
            <th class="col-sm-2"></th>
        </tr>
    </thead>
    <tbody>
        {% for entry in address_book %}
        <tr>
            <th class="col-sm-2">
                {{ entry }}
            </th>
            <td class="col-sm-4">
                {{ entry.address }}
            </td>
            <td class="col-sm-2">
                {% if user.default_billing_address == entry %}
                <span class="label label-default">{% trans "Default" %}</span>
                {% else %}
                <form method="post" action="{% url "profile:address-make-default" pk=entry.pk purpose="billing" %}" class="form-inline form-horizontal">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-sm">{% trans "Make default" %}</button>
                </form>
                {% endif %}
            </td>
            <td class="col-sm-2">
                {% if user.default_shipping_address == entry %}
                <span class="label label-default">{% trans "Default" %}</span>
                {% else %}
                <form method="post" action="{% url "profile:address-make-default" pk=entry.pk purpose="shipping" %}" class="form-inline form-horizontal">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default btn-sm">{% trans "Make default" %}</button>
                </form>
                {% endif %}
            </td>
            <td class="col-sm-2">
                <a href="{% url 'profile:address-edit' pk=entry.pk slug=entry.get_slug %}" class="btn btn-default btn-sm"><i class="glyphicon glyphicon-edit"></i> {% trans "Edit" %}</a>
                <a href="{% url 'profile:address-delete' pk=entry.pk slug=entry.get_slug %}" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-remove"></i> {% trans "Delete" %}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div>
    <a href="{% url 'profile:address-create' %}" class="btn btn-default"><i class="glyphicon glyphicon-plus-sign"></i> {% trans "Add new address" %}</a>
</div>

saleor/userprofile/templates/userprofile/ajax/orders.html
{% load i18n %}
{% load gross from prices %}
<table class="table table-striped">
    <thead>
        <tr>
            <th class="col-sm-2">
                {% trans "Order #" %}
            </th>
            <th class="col-sm-2">
                {% trans "Date" %}
            </th>
            <th class="col-sm-2">
                {% trans "Price" %}
            </th>
            <th class="col-sm-2">
                {% trans "Status" %}
            </th>
            <th class="col-sm-2">
                {% trans "Last status change" %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
            <tr>
                <td class="col-sm-2">
                    <a href="{{ order.get_absolute_url }}">{{ order }}</a>
                </td>
                <td class="col-sm-2">
                    {{ order.created }}
                </td>
                <td class="col-sm-2">
                    {% gross order.get_total %}
                </td>
                <td class="col-sm-2">
                    <span class="label label-default">{{ order.get_status_display }}</span>
                </td>
                <td class="col-sm-2">
                    {{ order.last_status_change }}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>